language: node_js
node_js:
  - node

install:
  - npm install

script:
  - npm run build:noprogress

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
